# Generated by Django 4.0.5 on 2022-07-27 11:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('question', '0002_question_answers_count'),
    ]

    operations = [
        migrations.AddField(
            model_name='maincategory',
            name='slug',
            field=models.SlugField(default='coding'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='subcategory',
            name='slug',
            field=models.SlugField(default='python'),
            preserve_default=False,
        ),
    ]
